package com.example.search;

public class CountriesList {
public static String[] countries = {"Sankaran V",
	"Daphne Lopez",
	"Bimal Kumar Ray",
	"Ganesan K.",
	"Hari Ram Vishwakarma",
	"Saravanan R",
	"Aswani Kumar Cherukuri",
	"Subha S.",
	"Dhenesh Virallikattur Subramanian",
	"Dhinesh Babu L.D.",
	"Dinakaran M.",
	"Jeyanthi N.",
	"Krishna Chandramouli",
	"Neelu Khare",
	"Sathiyamoorthy E.",
	"Valarmathi.B",
	"Balamurugan B.",
	"Chandra Mouliswaran S.",
	"Jagadeesh G.",
	"John Singh K.",
	"Kamalakannan J.",
	"Mohan Kumar P.",
	"Mythili N.",
	"Persis Urbana Ivy B.",
	"Pounambal M.",
	"Ramesh P S",
	"Ranichandra C.",
	"Sumathy S.",
	"Thanapal P.",
	"Thandeeswaran R.",
	"Ushadevi G.",
	"Vijayan R.",
	"Agilandeeswari.L",
	"Alagiri I.",
	"Anusha K.",
	"Arivu Selvan K.",
	"Bhavani.S",
	"Brindha.K",
	"Chandrasekhar.U",
	"Chiranji Lal Chowdhary",
	"Deepa. K",
	"Durai Raj Vincent P.M.",
	"Gitanjali J.",
	"Gunasekaran G.",
	"Hemalatha S.",
	"Indhumathi R",
	"Jasmine Norman",
	"Jayaram Reddy A.",
	"Kalaivani S.",
	"Karthikeyan P.",
	"Kavitha B.R ",
	"Kiruba Thangam R",
	"Kumar P.J.",
	"Kumaresan P.",
	"Mangayarkarasi R.",
	"Manikandan N.",
	"Manivannan.S.S",
	"Meenatchi.S",
	"Menaka S.",
	"Muthamil Selvan T",
	"Nadesh R.K.",
	"Navaneethan C",
	"Nirmala M.",
	"Nithya.S",
	"Parimala M.",
	"Prabhavathy P.",
	"Prabhu J.",
	"Prabukumar M.",
	"Pradeep Reddy. Ch",
	"Prasanna S.",
	"Priya. M",
	"Puviarasi G.",
	"Raghavan R.",
	"Ramya.G",
	"Santhi K.",
	"Saravanakumar K.",
	"Seetha R.",
	"Selva Rani B.",
	"Senthil Kumar K.",
	"Senthilkumar N.C.",
	"Senthil Kumar P.",
	"Senthil Kumaran U.",
	"Senthil Murugan B.",
	"Shashikiran V",
	"Sivakumar. N",
	"Sree Dharinya S.",
	"Srinivasa Perumal R.",
	"Sudha M.",
	"Sudha.S",
	"Sujatha R.",
	"Sumangali K.",
	"Swarna Priya R.M.",
	"Tapan Kumar Das",
	"Uma Maheswari G.",
	"Vani M.P.",
	"Vanitha M.",
	"Vanmathi.C",
	"Vijayalakshmi S.",
	"Vijayan E.",
	"Viswanathan P.",
	"Aarthy.S.L",
	"Abraham Paul",
	"Angulakshmi M.",
	"Anitha A.",
	"Asha N.",
	"Asha Jerlin M.",
	"Barath P.",
	"Benjula Anbu Malar M.B.",
	"ChandraSegar.T",
	"Chandrasekar R",
	"Charanya.R",
	"Deepa M.",
	"Deepa N",
	"Dinesh Kumar R",
	"Ephzibah E.P.",
	"Gundala Swathi",
	"Jayalakshmi P.",
	"Karthikeyan.J",
	"Krithika.L.B",
	"Kumaran U",
	"Lakshmanna K",
	"Lawanya Shri.M",
	"Mahadevan R",
	"Malathy E.",
	"Mareeswari V.",
	"Mary Mekala A.",
	"Naga Raja G",
	"Nallakaruppan M K",
	"Nancy Victor",
	"Narmadha. K",
	"Priya V.",
	"Priyadarsini S",
	"Ragendhu S P",
	"Rahamathunnisa.U",
	"Rajesh kaluri",
	"Rajeswari C",
	"Rama Prabha K P",
	"Rathi R.",
	"Senthil Kumar. M",
	"Senthil Kumar N.",
	"Shynu P.G",
	"Siva Rama Krishnan Somayaji",
	"Sivashankari R.",
	"Srinivas Koppu",
	"Subhashini R.",
	"Sudheer K",
	"Sumathi D.",
	"Sureka S.",
	"TamilPriya.D",
	"Thilagavathi M.",
	"Thippa Reddy G",
	"Varalakshmi M.",
	"VarunKumar.M",
	"VijayaRani.A",
	"Anitha Kumari.A",
	"Deepa P",
	"Deepikaa.S",
	"Rajaprabha M.N.",
	"RenukaDevi.R",
	"Suba Shanthini S.",
	"Viswanathan R",
	"Prem Kumar Singh",
	"Arun K R",
	"Josiya Ancy J",
	"Hemavathi S",
	"Pushparaj R",
	"Janani V",
	"Sathish Kumar M",
	"Ebin Deni Raj ",
	"Gunasekaran M",
	"Sathya S",
	"Venkatraman ",
	"Vinoth Kumar",
	"Balaji S S",
	"Kishore Kumar",
	"MohanaPriya.J",
	"Brijendra Singh",
	"Magesh G",
	"KAVITHA.G",
	"Jayakumar.S",
	"Dhakshnamoorthy S",
	"Chitra M.",
	"Hariharan K",
	"Karthiga N",
	"Tamilvani V.",
	"Dhamodharan P",
	"Ganesh Prabu.S",
	"Lakshmi Narayanan J.",
	"Vimal Kumar M B",
	"Sakthivel",
	"Dhanasekar P",
	"Venkatesan P.V.",
	"Elangchezhian A",
	"Elangovan N.",
	"Jayakumar C",
	"Sivaprakash V"};
public static String[] abbreviations = { "SJT G22",
	"SJT 511 A19",
	"SJT Anx 101 A",
	"TIFAC",
	"SJT Anx 101 B",
	"SJT Anx 201 B",
	"SJT Anx 101 D",
	"SJT 313 A25",
	"SJT 116 A18",
	"SJT 511 A28",
	"SJT 210 A05",
	"SJT G24 H",
	"SJT 313 A27",
	"SJT 116 A13",
	"SJT G24 E",
	"SJT 111 A25",
	"SJT 511 A18",
	"SJT 111 A03",
	"SJT G24 G",
	"SJT 111 A38",
	"SJT 511 A20",
	"SJT 210 A16",
	"SJT 313 A06",
	"SJT 210 A24",
	"SJT G 24 C",
	"SJT G24 J",
	"SJT G24 A",
	"SJT 511 A29",
	"SJT 111 A08",
	"SJT G24 F",
	"SJT 111 A09",
	"SJT 210 A10",
	"SJT 116 A19",
	"SJT 210 A09",
	"SJT 111 A29",
	"SJT 310 A24",
	"SJT 116 A33",
	"SJT 210 A18",
	"SJT 116 A28",
	"SJT 116 A32",
	"SJT 310 A34",
	"SJT 210 A20",
	"SJT 313 A13",
	"SJT 313 A20",
	"SJT 313 A30",
	"SJT 116 A35",
	"SJT 111 A11",
	"SJT G24 D",
	"SJT 213 A35",
	"SJT 213 A20",
	"SJT 116 A09",
	"SJT 210 A01",
	"SJT 213 A27",
	"SJT 116 A24",
	"SJT 111 A17",
	"SJT 213 A26",
	"SJT 213 A05",
	"SJT 213 A11",
	"SJT 210 A12",
	"SJT 210 A17",
	"SJT 310 A26",
	"SJT 511 A11",
	"SJT 313 A10",
	"SJT 116 A37",
	"SJT 213 A24",
	"SJT 213 A36",
	"SJT 213 A22",
	"SJT 310 A02",
	"SJT 313 A36",
	"SJT 116 A10",
	"SJT 111 A14",
	"SJT G24 B",
	"SJT 210 A03",
	"SJT 116 A38",
	"SJT 313 A11",
	"SJT 310 A23",
	"SJT 213 A32",
	"SJT 310 A27",
	"SJT 111 A20",
	"SJT 313 A35",
	"SJT 210 A13",
	"SJT 313 A01",
	"SJT 411 A20",
	"SJT 413 A30",
	"SJT 111 A04",
	"SJT 210 A06",
	"SJT 210 A21",
	"SJT 111 A06",
	"SJT 116 A26",
	"SJT 210 A31",
	"SJT 313 A16",
	"SJT 111 A10",
	"SJT 111 A05",
	"SJT 210 A23",
	"SJT 313 A18",
	"SJT 313 A19",
	"SJT 111 A13",
	"",
	"SJT 313 A34",
	"SJT 116 A08",
	"SJT 511 A05",
	"SJT 210 A11",
	"SJT 116 A31",
	"SJT 310 A06",
	"SJT 213 A29",
	"SJT 111 A02",
	"SJT 310 A35",
	"SJT 310 A36",
	"SJT 116 A17",
	"SJT 116 A12",
	"SJT 116 A36",
	"SJT 310 A38",
	"SJT 116 A05",
	"SJT 210 A36",
	"SJT 210 A32",
	"SJT 213 A34",
	"SJT 310 A16",
	"SJT 313 A14",
	"SJT 111 A01",
	"SJT 111 A16",
	"SJT 111 A27",
	"SJT 313 A05",
	"SJT 613 A",
	"SJT 116 A16",
	"SJT 210 A30",
	"SJT 310 A03",
	"SJT 116 A21",
	"SJT 116 A20",
	"SJT 213 A16",
	"SJT 111 A15",
	"SJT 411 A31",
	"SJT 116 A14",
	"SJT 116 A23",
	"SJT 116 A03",
	"SJT 111 A18",
	"SJT 111 A31",
	"SJT 111 A33",
	"SJT 213 A25",
	"SJT 116 A11",
	"SJT 310 A22",
	"SJT 116 A02",
	"SJT 313 A37",
	"SJT 116 A34",
	"SJT 111 A12",
	"SJT 411 A07",
	"SJT 111 A32",
	"SJT 213 A30",
	"SJT 213 A31",
	"SJT 411 A08",
	"SJT 310 A14",
	"SJT 111 A37",
	"SJT 310 A05",
	"SJT 213 A06",
	"SJT 210 A08",
	"SJT 213 A02",
	"SJT 210 A34",
	"SJT 313 A15",
	"SJT 310 A17",
	"SJT 411 A18",
	"SJT 310 A18",
	"SJT 116 A15",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"",
	"SJT G19A",
	"SJT 213 A01",
	"SJT 213 A01",
	"SJT 213 A01",
	"SJT 213 A01",
	"SJT 213 A01",
	"SJT 510 A20",
	"SJT 510 A01",
	"SJT 510 A19",
	"SJT 510 A23",
	"SJT 510 A03",
	"SJT G22",
	"SJT G23",
	"SJT G23",
	"SJT G23",
	"SJT G23",
	"SJT G22",
	"SJT 217A",
	"SJT 120A",
	"SJT 121",
	"SJT G18A",
	"SJT G22",
	"SJT G23",
	"SJT 217A",
	"SJT G23",
	"SJT G23",
	"SJT 120A" };

public static String[] gen = { "Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Mr.",
	"Mr.",
	"Ms.",
	"Ms.",
	"Mr.",
	"Ms.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Prof.",
	"Mr.",
	"Mrs.",
	"Mr.",
	"Ms.",
	"Ms.",
	"Mr.",
	"Mr.",
	"Mr",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr.",
	"Mr." };

public static String[] sex = { "M",
	"F",
	"M",
	"M",
	"M",
	"M",
	"M",
	"F",
	"M",
	"M",
	"M",
	"F",
	"M",
	"F",
	"M",
	"F",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"F",
	"F",
	"F",
	"M",
	"F",
	"F",
	"M",
	"M",
	"F",
	"M",
	"F",
	"M",
	"F",
	"M",
	"F",
	"F",
	"M",
	"M",
	"F",
	"M",
	"F",
	"M",
	"F",
	"F",
	"F",
	"M",
	"F",
	"M",
	"F",
	"F",
	"M",
	"M",
	"F",
	"M",
	"M",
	"F",
	"F",
	"M",
	"M",
	"M",
	"F",
	"F",
	"F",
	"F",
	"M",
	"M",
	"M",
	"M",
	"F",
	"F",
	"M",
	"F",
	"F",
	"M",
	"F",
	"F",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"F",
	"M",
	"F",
	"F",
	"F",
	"F",
	"F",
	"M",
	"F",
	"F",
	"F",
	"F",
	"F",
	"M",
	"M",
	"F",
	"M",
	"F",
	"F",
	"F",
	"F",
	"M",
	"F",
	"M",
	"M",
	"F",
	"F",
	"F",
	"M",
	"F",
	"F",
	"F",
	"M",
	"F",
	"M",
	"M",
	"F",
	"M",
	"F",
	"F",
	"F",
	"M",
	"M",
	"F",
	"F",
	"F",
	"F",
	"F",
	"F",
	"M",
	"F",
	"F",
	"F",
	"M",
	"M",
	"M",
	"M",
	"F",
	"M",
	"F",
	"M",
	"F",
	"F",
	"F",
	"F",
	"M",
	"F",
	"M",
	"F",
	"F",
	"F",
	"F",
	"F",
	"F",
	"F",
	"M",
	"M",
	"M",
	"F",
	"F",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"F",
	"M",
	"M",
	"F",
	"M",
	"M",
	"F",
	"M",
	"F",
	"F",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M",
	"M" };

public static String[] designation = { "Senior Professor & Dean",
	"Professor & Assistant Dean",
	"Senior Professor",
	"Senior Professor",
	"Senior Professor",
	"Senior Professor",
	"Professor",
	"Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asso. Professor",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Sel. Grade",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst. Prof. Senior",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst.Professor",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Research Associate",
	"Research Associate",
	"Research Associate",
	"Research Associate",
	"Research Associate",
	"Research Associate",
	"Research Associate",
	"Research Associate",
	"Research Assistant (ICMR)",
	"Image Infotainment",
	"Image Infotainment",
	"Image Infotainment",
	"Image Infotainment",
	"Image Infotainment",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"Asst. Prof. Junior",
	"School Manager",
	"DEO",
	"DEO",
	"DEO",
	"DEO",
	"Junior Assistant (Trainee)",
	"Technical Officer",
	"Technical Officer",
	"Technical Officer",
	"Lab Assistant",
	"Attender (Sr. Grade)",
	"Attender (Sr. Grade)",
	"Attender",
	"Attender",
	"Attender",
	"Attender" };

public static String[] email = { "dean.site@vit.ac.in",
	"daphnelopez@vit.ac.in",
	"bimalkumarray@vit.ac.in",
	"kganesan@vit.ac.in",
	"hrvishwakarma@vit.ac.in",
	"rsaravanan@vit.ac.in",
	"aswani@vit.ac.in",
	"ssubha@vit.ac.in",
	"dheneshvsubramanian@vit.ac.in",
	"lddhineshbabu@vit.ac.in",
	"dinakaran.m@vit.ac.in",
	"njeyanthi@vit.ac.in",
	"krishna.c@vit.ac.in",
	"neelu.khare@vit.ac.in",
	"esathiyamoorthy@vit.ac.in",
	"valarmathi.b@vit.ac.in",
	"balamuruganb@vit.ac.in",
	"chandramouliswaran@vit.ac.in",
	"gjagadeesh@vit.ac.in",
	"johnsingh.k@vit.ac.in",
	"jkamalakannan@vit.ac.in",
	"pmohankumar@vit.ac.in",
	"nmythili@vit.ac.in",
	"persis.b@vit.ac.in",
	"mpounambal@vit.ac.in",
	"ramesh.ps@vit.ac.in",
	"cranichandra@vit.ac.in",
	"ssumathy@vit.ac.in",
	"thanapal.p@vit.ac.in",
	"rthandeeswaran@vit.ac.in",
	"ushadevi.g@vit.ac.in",
	"rvijayan@vit.ac.in",
	"agila.l@vit.ac.in",
	"ialagiri@vit.ac.in",
	"anusha.k@vit.ac.in",
	"karivuselvan@vit.ac.in",
	"bhavani.s@vit.ac.in",
	"brindha.k@vit.ac.in",
	"u.chandrasekhar@vit.ac.in",
	"chiranji.lal@vit.ac.in",
	"deepa.k@vit.ac.in",
	"pmvincent@vit.ac.in",
	"gitanjalij@vit.ac.in",
	"ggunasekaran@vit.ac.in",
	"shemalatha@vit.ac.in",
	"indhumathi.r@vit.ac.in",
	"jasmine@vit.ac.in",
	"ajayaramreddy@vit.ac.in",
	"kalaivanis@vit.ac.in",
	"pkarthikeyan@vit.ac.in",
	"kavitha.br@vit.ac.in",
	"rkirubathangam@vit.ac.in",
	"pjkumar@vit.ac.in",
	"pkumaresan@vit.ac.in",
	"rmangayarkarasi@vit.ac.in",
	"manikandan.n@vit.ac.in",
	"manivannan.ss@vit.ac.in",
	"meenatchi.s@vit.ac.in",
	"smenaka@vit.ac.in",
	"tmuthamilselvan@vit.ac.in",
	"rknadesh@vit.ac.in",
	"navaneethan.c@vit.ac.in",
	"mnirmala@vit.ac.in",
	"nithya.s@vit.ac.in",
	"parimala.m@vit.ac.in",
	"pprabhavathy@vit.ac.in",
	"j.prabhu@vit.ac.in",
	"mprabukumar@vit.ac.in",
	"pradeep@vit.ac.in",
	"sprasanna@vit.ac.in",
	"priya.m@vit.ac.in",
	"gpuviarasi@vit.ac.in",
	"rraghavan@vit.ac.in",
	"ramya.g@vit.ac.in",
	"ksanthi@vit.ac.in",
	"ksaravanakumar@vit.ac.in",
	"rseetha@vit.ac.in",
	"bselvarani@vit.ac.in",
	"ksenthilkumar@vit.ac.in",
	"ncsenthilkumar@vit.ac.in",
	"psenthilkumar@vit.ac.in",
	"usenthilkumaran@vit.ac.in",
	"senthilmurugan.b@vit.ac.in",
	"shashikiran@vit.ac.in",
	"nsivakumar@vit.ac.in",
	"ssreedharinya@vit.ac.in",
	"r.srinivasaperumal@vit.ac.in ",
	"msudha@vit.ac.in",
	"sudha.s@vit.ac.in",
	"r.sujatha@vit.ac.in",
	"ksumangali@vit.ac.in",
	"swarnapriya.rm@vit.ac.in",
	"tapan.das@vit.ac.in",
	"g.umamaheswari@vit.ac.in",
	"mpvani@vit.ac.in",
	"mvanitha@vit.ac.in",
	"vanmathi.c@vit.ac.in",
	"vijayalakshmis@vit.ac.in",
	"evijayan@vit.ac.in",
	"pviswanathan@vit.ac.in",
	"aarthy.sl@vit.ac.in",
	"abrahampaul@vit.ac.in",
	"angulakshmi.m@vit.ac.in",
	"aanitha@vit.ac.in",
	"nasha@vit.ac.in",
	"ashajerlin.m@vit.ac.in",
	"pbarath@vit.ac.in",
	"mbbenjulaanbumalar@vit.ac.in",
	"chandrasegar.t@vit.ac.in",
	"chandrasekar.r@vit.ac.in",
	"charanya.r@vit.ac.in",
	"mdeepa@vit.ac.in",
	"deepa.rajesh@vit.ac.in",
	"dineshkumar.r@vit.ac.in",
	"ep.ephzibah@vit.ac.in",
	"gundalaswathi@vit.ac.in",
	"pjayalakshmi@vit.ac.in",
	"karthikeyan.j@vit.ac.in",
	"krithika.lb@vit.ac.in",
	"kumaran.u@vit.ac.in",
	"lakshman.kuruva@vit.ac.in",
	"kmlavanya@vit.ac.in",
	"mahadevan@vit.ac.in",
	"e.malathy@vit.ac.in",
	"vmareeswari@vit.ac.in",
	"amarymekala@vit.ac.in",
	"nagaraja.g@vit.ac.in",
	"nallakaruppan.mk@vit.ac.in",
	"nancyvictor@vit.ac.in",
	"narmadha.k@vit.ac.in",
	"vpriyacse@vit.ac.in",
	"priyadarsini.s@vit.ac.in",
	"ragendhusp@vit.ac.in",
	"rahamathu.u@vit.ac.in",
	"rajesh.kaluri@vit.ac.in",
	"rajeswari.c@vit.ac.in",
	"ramaprabha.kp@vit.ac.in",
	"rathi.r@vit.ac.in",
	"senthilkumar.mohan@vit.ac.in",
	"senthilkumar.n@vit.ac.in",
	"pgshynu@vit.ac.in",
	"siva.s@vit.ac.in",
	"sivashankari.r@vit.ac.in",
	"srinukoppu@vit.ac.in",
	"rsubhashini@vit.ac.in",
	"sudheer.k@vit.ac.in ",
	"dsumathi@vit.ac.in",
	"ssureka@vit.ac.in",
	"tamilpriya.d@vit.ac.in",
	"mthilagavathi@vit.ac.in",
	"thippareddy.g@vit.ac.in",
	"mvaralakshmi@vit.ac.in",
	"varunkumar.m@vit.ac.in",
	"vijayarani.a@vit.ac.in",
	"anithakumari.a@vit.ac.in",
	"deepa.p@vit.ac.in",
	"deepikaa.s@vit.ac.in",
	"mnrajaprabha@vit.ac.in",
	"renukadevi.r@vit.ac.in",
	"subashanthini@vit.ac.in",
	"viswanathan.r@vit.ac.in",
	"premkumarsingh@vit.ac.in",
	"arun.kr@vit.ac.in / aruun005@gmail.com",
	"josiya.ancy@gmail.com",
	"hemavathi.sekar@vit.ac.in / hems.288@gmail.com",
	"pushparaj.r2013@vit.ac.in / pushparaj1315@gmail.com",
	"jananiv91@gmail.com",
	"sathish89visit@gmail.com",
	"ebindraj@gmail.com",
	"gunavit@gmail.com",
	"sathyasripathi@gmail.com",
	"",
	"",
	"",
	"",
	"mohanapriya.j@vit.ac.in",
	"brijendrasingh@vit.ac.in",
	"magesh.g@vit.ac.in",
	"kavitha.g@vit.ac.in",
	"jayakumars@vit.ac.in",
	"dhakshnaamie@vit.ac.in",
	"mchitra@vit.ac.in",
	"hariharan.k@vit.ac.in",
	"karthiga.n@vit.ac.in",
	"tamilvani.v@vit.ac.in",
	"pdhamodharan@vit.ac.in",
	"ganeshprabu.s@vit.ac.in",
	"jlakshminarayanan@vit.ac.in",
	"vimalkumar.mb@vit.ac.in",
	"sakthivel.s@vit.ac.in",
	"pdhanasekaran@vit.ac.in",
	"pvvenkatesan@vit.ac.in",
	"elanchezhiyan.a@vit.ac.in ",
	"nelango@vit.ac.in",
	"jayakumar.c@vit.ac.in",
	"sivaprakash.v@vit.ac.in" };
 }
